version: '3.1'
services:
  web:
    image: odoo:16.0
    container_name: odoo_16
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=mydb
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - ../addons:/mnt/extra-addons
    restart: always
    networks:
      - avfPrivateNetwork

  mydb:
    image: postgres:14
    container_name: avf_postgres_14
   
    expose:
      - 5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    restart: always             # run as a service
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - avfPrivateNetwork
volumes:
  web:
  mydb:

networks:
  avfPrivateNetwork:
    driver: bridge
