version: '3.1'
services:
  web:
    image: odoo:15.0
    container_name: odoo_15
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    env_file: .env
    restart: always
    #environment:
     # - PASSWORD_FILE=/run/secrets/postgresql_password
    #secrets:
     # - postgresql_password
    networks:
      - avfPrivateNetwork
  db:
    image: postgres:14
    container_name: avf_postgres_14
    env_file: .env
    restart: always
    #environment:
     # - POSTGRES_DB=postgres
     # - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      #- POSTGRES_USER=odoo
      #- PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data-n:/var/lib/postgresql/data/pgdata
    #secrets:
     # - postgresql_password
    networks:
      - avfPrivateNetwork

#secrets:
  #postgresql_password:
    #file: odoo_pg_pass

networks:
  avfPrivateNetwork:
    driver: bridge